spring:
  application:
    name:
      spring-ai-openai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5-mini
          temperature: 1
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client: DEBUG