spring:
  application:
    name: spring-ai-wip
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: 8090

