spring:
  application:
    name: springai-with-ollama
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:1b
server:
  port: 8888

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

